load("@rules_cc//cc:defs.bzl", "cc_binary")
cc_binary(
    name = "hello-world",
    srcs = ["hello-world.cc", "matrix.h"],
)

cc_binary(
    name = "hello-matrix",
    srcs = ["hello-matrix.cc", "matrix.cc", "matrix.h"],
)



